# Generated by Django 2.0.3 on 2018-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_Payable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paydate',
            field=models.IntegerField(),
        ),
    ]
